title: Sunday Open League
description: Vancouver Curling Club 6:45pm Sundays
google_analytics:
theme: jekyll-theme-time-machine

exclude:
- README.md

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji


twitter:
  username: vccsundayopen

social: # jekyll-seo-tag > social overrides
  name: VCC Sunday Open 
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/vccsundayopen
    - https://instagram.com/vccsundayopen

sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Vancouver # Timezone for blog posts and alike


encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "VCC Sunday Open" # Site name or title, also used in jekyll-seo-tag
logo: "assets/sundayopenlogo.jpg" # Site logo, also used in jekyll-seo-tag
description: "Sunday Open League at Vancouver Curling Club. Sundays at 6:45pm" # Site description and default description, also used in jekyll-seo-tag
url: "https://alembic.darn.es" # Site url, also used in jekyll-seo-tag
baseurl: ""
email: "info@vccsundayopen.club"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

navigation_header:
  Home: /
  Past Champions: pastchamps.html
  #Blog: /blog/
  #Categories: /categories/
  #Search: /search/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/vccsundayopen
  Instagram: https://instagram.com/vccsundayopen
  #RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  Instagram: "#3B5998"
  #Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  Email: "#36465D"
